const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {handle}=require('./service.cjs'),{LocalStore}=require('./storage.cjs');
const webp=Buffer.from('UklGRiIAAABXRUJQVlA4IBYAAAAwAQCdASoBAAEADsD+JaQAA3AAAAAA','base64');
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'wedding-admin-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const store=new LocalStore(dir);const call=async(method,pathname,body,version,owner=true)=>{const r=await handle({method,pathname,owner,headers:{'x-admin-request':'1',...(version?{'if-match':String(version)}:{})},bytes:body===undefined?Buffer.alloc(0):Buffer.isBuffer(body)?body:Buffer.from(JSON.stringify(body))},store);return {...r,data:r.headers['Content-Type']==='application/json'?JSON.parse(r.body):r.body};};return {store,call,dir};}
test('owner authorization and CSRF guard block anonymous writes',async t=>{const {call,store}=await fixture(t);assert.equal((await call('GET','/api/admin/stories',undefined,undefined,false)).status,401);assert.equal((await call('POST','/api/admin/stories',{},undefined,false)).status,401);assert.equal((await handle({method:'POST',pathname:'/api/admin/stories',owner:true},store)).status,403);assert.equal((await call('GET','/api/stories',undefined,undefined,false)).data.stories.length,3);});
test('upload → draft → publish → rename/reorder/cover → unpublish → delete persists',async t=>{
 const {call,dir}=await fixture(t);let story=(await call('POST','/api/admin/stories')).data.story;const base='/api/admin/stories/'+story.id;
 story=(await call('POST',base+'/photos',webp,story.version)).data.story;const first=story.draft.photos[0];
 assert.equal((await call('GET',first.url,undefined,undefined,false)).status,404);
 assert.equal((await call('GET',first.url.replace('/media/','/admin/media/'))).status,200);
 story=(await call('POST',base+'/photos',webp,story.version)).data.story;
 let draft={...story.draft,names:{en:'Test couple',pl:'Para',uk:'Пара'},date:'2026-10-05',photos:[...story.draft.photos].reverse(),cover:story.draft.photos[1].id};
 story=(await call('PUT',base,draft,story.version)).data.story;
 assert.equal((await call('GET','/api/stories')).data.stories.some(s=>s.id===story.id),false);
 story=(await call('POST',base+'/publish',draft,story.version)).data.story;
 assert.equal((await call('GET',first.url,undefined,undefined,false)).status,200);
 const published=(await call('GET','/api/stories')).data.stories.find(s=>s.id===story.id);assert.equal(published.cover,draft.cover);assert.deepEqual(published.photos,draft.photos);
 draft={...draft,names:{en:'Renamed couple',pl:'',uk:''},photos:[draft.photos[0]]};story=(await call('PUT',base,draft,story.version)).data.story;
 assert.equal((await call('GET','/api/stories')).data.stories.find(s=>s.id===story.id).names.en,'Test couple');
 assert.equal((await call('GET',first.url,undefined,undefined,false)).status,200);
 story=(await call('POST',base+'/publish',draft,story.version)).data.story;
 assert.equal((await call('GET',first.url,undefined,undefined,false)).status,404);await assert.rejects(fs.access(path.join(dir,'photos',first.id)));
 const reopened=new LocalStore(dir);assert.equal((await reopened.read()).data.stories.find(s=>s.id===story.id).published.names.en,'Renamed couple');
 story=(await call('POST',base+'/unpublish',undefined,story.version)).data.story;assert.equal((await call('GET','/api/stories')).data.stories.some(s=>s.id===story.id),false);
 assert.equal((await call('DELETE',base,undefined,story.version)).status,200);assert.equal((await fs.readdir(path.join(dir,'photos'))).length,0);
});
test('stale saves and invalid uploads/foreign photo references are rejected',async t=>{const {call}=await fixture(t);let s=(await call('POST','/api/admin/stories')).data.story;const base='/api/admin/stories/'+s.id;assert.equal((await call('POST',base+'/photos',Buffer.from('<svg>bad</svg>'),s.version)).status,400);s=(await call('POST',base+'/photos',webp,s.version)).data.story;assert.equal((await call('PUT',base,s.draft,1)).status,409);assert.equal((await call('PUT',base,{...s.draft,photos:[{id:'foreign'}]},s.version)).status,400);assert.equal((await call('PUT',base,{...s.draft,date:'2026-02-31'},s.version)).status,400);assert.equal((await call('PUT',base,{...s.draft,photos:[s.draft.photos[0],s.draft.photos[0]]},s.version)).status,400);});
test('concurrent manifest updates cannot silently overwrite each other',async t=>{const {store}=await fixture(t);const a=await store.read(),b=await store.read();await store.write(a.data,a.etag);await assert.rejects(store.write(b.data,b.etag),{status:409});});
test('portfolio migration, private uploads, ordering, deletion and empty publication are independent of stories',async t=>{
 const {call,store,dir}=await fixture(t);
 const originalStories=structuredClone((await store.read()).data.stories);
 assert.equal((await call('GET','/api/admin/portfolio',undefined,undefined,false)).status,401);
 assert.equal((await call('GET','/api/portfolio')).data.photos.length,15);
 let portfolio=(await call('GET','/api/admin/portfolio')).data.story;
 portfolio=(await call('POST','/api/admin/portfolio/photos',webp,portfolio.version)).data.story;
 const uploaded=portfolio.draft.photos.at(-1);
 assert.equal((await call('GET',uploaded.url,undefined,undefined,false)).status,404);
 assert.equal((await call('GET',uploaded.url.replace('/media/','/admin/media/'))).status,200);
 const reordered={photos:[uploaded,...portfolio.draft.photos.slice(1,-1).reverse()]};
 portfolio=(await call('PUT','/api/admin/portfolio',reordered,portfolio.version)).data.story;
 assert.equal((await call('GET','/api/portfolio')).data.photos[0].id,'sample-139');
 assert.equal((await call('POST','/api/admin/portfolio/publish',reordered,1)).status,409);
 assert.equal((await call('PUT','/api/admin/portfolio',{photos:[{id:'foreign'}]},portfolio.version)).status,400);
 portfolio=(await call('POST','/api/admin/portfolio/publish',reordered,portfolio.version)).data.story;
 assert.deepEqual((await call('GET','/api/portfolio')).data.photos,reordered.photos);
 assert.equal((await call('GET',uploaded.url,undefined,undefined,false)).status,200);
 portfolio=(await call('PUT','/api/admin/portfolio',{photos:[]},portfolio.version)).data.story;
 assert.equal((await call('GET',uploaded.url,undefined,undefined,false)).status,200);
 portfolio=(await call('POST','/api/admin/portfolio/publish',{photos:[]},portfolio.version)).data.story;
 assert.deepEqual((await call('GET','/api/portfolio')).data.photos,[]);
 assert.equal((await call('GET',uploaded.url,undefined,undefined,false)).status,404);
 await assert.rejects(fs.access(path.join(dir,'photos',uploaded.id)));
 assert.deepEqual((await store.read()).data.stories,originalStories);
 assert.deepEqual((await new LocalStore(dir).read()).data.portfolio.published.photos,[]);
});
